* Mud Rally

Mud Rally is a retro style 320x240 [[https://en.wikipedia.org/wiki/Demolition_derby][demolition derby]] racing game built using [[https://love2d.org/][LÖVE]]
and written in [[http://wwww.fennel-lang.org][Fennel]].

It is under development, and there are no screenshots, so don't try it, and
don't send me any questions!

To curious the wanderers that have somehow ended up here wanting to try it
anyway, clone the repo, install LÖVE, and run `love .` in the root
directory. You can do absolutely nothing of interest yet.

This project is based on the glorious [[https://gitlab.com/alexjgriffith/min-love2d-fennel][Minimal Fennel Love2D setup]] by Alexander
Griffith, which is orignally based on Phil Hagelberg's [[https://gitlab.com/technomancy/exo-encounter-667/][exo-encounter-667]] game.

** Trivia

I began working on this game in 1999 or so, and began working on it after a long
while.

** Attributions

This game has used or is currently using these wonderful tools:

- [[http://www.love2d.org][LÖVE]] for the game framework
- [[https://www.mapeditor.org/][Tiled]] and [[https://github.com/karai17/Simple-Tiled-Implementation][STI]] for map tiles
- [[https://github.com/HDictus/breezefield][breezefield]] for physics

... and several other libraries such as [[https://github.com/rxi/lume][Lume]].


*** Art & Tilesets 

- The current tileset is [[https://opengameart.org/content/consolidated-hard-vacuum-terrain-tilesets][Hard Vacuum]] by Daniel Cook ([[http://lostgarden.com][lostgarden.com]])

